### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ynchan** [IBM-MIL/IBM-Ready-App-for-Venue#14]
I'm getting this error message when attempting a build in Xcode, how do I rebuild the SDK?

/IBM-Ready-App-for-Venue-master/iOS/Venue/DataSources/PresenceInsightsManager.swift:7:8: Module file was created by an older version of the compiler; rebuild 'PresenceInsightsSDK' and try again: /IBM-Ready-App-for-Venue-master/iOS/Venue/Frameworks/PresenceInsightsSDK.framework/Modules/PresenceInsightsSDK.swiftmodule/x86_64.swiftmodule

**Comment by craigkj312** [comment]
This is an after-effect of the Presence Insights service being removed from Bluemix. The application has now been updated to remove this service.
